#Taking input from the user
print("Please enter the following information:")
firstn = input("First Name: ")
lastn = input("Last Name: ")
email = input("Email address: ")
phonenum = input("Phone Number: ")
job = input("Occupation: ")
id = input ("ID: ")
hairc = input ("Hair Color: ")
eyesc = input ("Eyes Color: ")
month = input ("Month: ")
y_n = input ("Training: ")
#Output
print()
print("The ID Card is:")
print("----------------------------------------")
print(f"{lastn.upper()}, {firstn.capitalize()}")

print("Occupation: " + job.title())
print("ID: " + id)
print()
print("Email address: " + email.lower())
print("Phone Number: " + phonenum)
print()
print(f"Hair: {hairc:15} Eyes: {eyesc}")
print(f"Month: {month:14} Training: {y_n}")
print("----------------------------------------")

